#define VERSION_MAJOR 0
#define VERSION_MINOR 6
#define VERSION_PATCH 0

#define WIN_RESOURCE_VERSION VERSION_MAJOR,VERSION_MINOR,VERSION_PATCH,0

#define STR_HELPER(x) #x
#define STR(x) STR_HELPER(x)

#define WIN_RESOURCE_VERSION_STR STR(VERSION_MAJOR) "." STR(VERSION_MINOR) "." STR(VERSION_PATCH) ".0"